- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 2.5h # ADT-Tweak 2.5h
#    - !type:RoleTimeRequirement
#      role: JobStationEngineer
#      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h # ADT-Tweak
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
    - !type:SpeciesRequirement # ADT-Tweak
      inverted: true
      species:
      - Vox
      #ADT tweak end
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    # eyes: ClothingEyesGlassesMeson #ADT-Tweak - заменено на выбор
    # ears: ClothingHeadsetCE # ADT tweak
# ADT-Tweak-start по причине того, что ассистент и остальной состав ИО спавнится с двумя поясами, если их выбрать в лоудауте
    # belt: ClothingBeltUtilityEngineering
# ADT-Tweak-end
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout

#ADT tweak start
- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
#ADT tweak end